### ISSUE TITLE
Example service list XML has invalid values for ContentGuideSource and ContentGuideServiceRef

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#10]
The example service list includes one Content Guide Server
```
  <ContentGuideSource CGSID="cgid-1">
    <ProviderName>DVB-I Reference Application</ProviderName>
    <ScheduleInfoEndpoint contentType="application/xml">
      <URI>https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/schedule.php</URI>
    </ScheduleInfoEndpoint>
  </ContentGuideSource>
```
but there are no services that refer to this CG server (it should be referred to through the `<ContentGuideSourceRef>` elements

Also the <service> elements contain `<ContentGuideServiceRef>` elements, the value of that should be the `<UniqueIdentifier>` of another <service>
```
  <Service version="1">
    <UniqueIdentifier>sid1</UniqueIdentifier>
       . . .
    <ContentGuideServiceRef>cgsid_1</ContentGuideServiceRef>
  </Service>
  <Service version="1">
    <UniqueIdentifier>sid2</UniqueIdentifier>
       . . . 
    <ContentGuideServiceRef>cgsid_2</ContentGuideServiceRef>
  </Service>
  <Service version="1">
    <UniqueIdentifier>sid3</UniqueIdentifier>
      . . . 
    <ContentGuideServiceRef>cgsid_3</ContentGuideServiceRef>
  </Service>
  . . . 
```

**Comment by paulhiggs** [comment]
A brief explanation

- The `<ContentGuideSource>` allows the definition of a single set of query URLs to be used for many services, i.e. RAI1, RAI2, RAI3 may all use the same CG server so this saves replicating the query URIs in each `<Service>`. Instead a `<ContentGuideSourceRef>` element gets added, the values of the element being the `@CGSID` value from a `<ContentGuideSource>` in this service list 

- The `<ContentGuideServiceRef>` is used for `sid=` query parameter instead of the `<UniqueIdentifier>`. This can be used in several ways, (1) the content guide server is unaware of the value given in the `<UniqueIdentifier>` so a different value is given in the `<ContentGuideServiceRef>` and (2) in situations where there are two editorially equivelant services but with some other different characteristics, i.e. RAI4-SD at LCN 4 and RAI4-HD at LCN 104 - in this case the each `<Service>` will have a `<ContentGuideServiceRef>RAI4</ContentGuideServiceRef>` value which will retrieve the same EPG data for both services.

**Comment by sofia-tsa** [comment]
I assumed that the ContentGuideSourceRef would be used only if several ContentGuideSource-elements were defined in the ContentGuideSourceList-element but if only a single ContentGuideSource is defined for the Service list then it would be a global value.

Why I reached that conclusion is the definition of the ContentGuideSourceRef: "The ID referencing a ContentGuideSource defined in the ContentGuideSourceList." If there is  only a single ContentGuideSource-defined in the service list instead of the ContentGuideSourceList,  then the reference would point to nowhere.

I can add the ContentGuideServiceRef to the Service-elements in next update.

**Comment by paulhiggs** [comment]
I need to take a look at the definition of `<ContentGuideSource>` in the `<ServiceList>`. It reads as though it could be a global content guide server for all services (rather than have all services refer to a single element in the `<ContentGuideSourceList>`

**Comment by paulhiggs** [comment]
A177r1 now says

> `<ContentGuideSource >`: The details of a content guide source providing schedule and programme metadata for all services in this service list that do not have their own `ContentGuideSource` element.

Thus when defined in the service list, this does provide EPG endpoints for all services that do not define their own, either through `<ContentGuideSource>` or `<ContentGuideSourceRef>`
