### ISSUE TITLE
Implementing the Network service discovery using DNS-SD/mDNS

### ISSUE THREAD

**Issue by juhajoki** [DVBProject/DVB-I-Reference-Client#106]
implement in the DVB-I client the Device discovery protocol as specified in DVB-NIP A180r1.1 bluebook, chapter 11.1.2.

The DVB-I client shall enable this feature at any time to discover potential NIP (or HB) Gateway on the same local network.
If only one NIP GW is detected, then the application shall add the Service Lists proposed by the “NIP local SLR”.
If several ones are detected, the application shall add the Service Lists proposed by each NIP GW.

NIP GW detection and getting the accessible orbital position(s) (See: 11.1.2.4 – 1), makes a query to connected CSR to
add Service Lists with the orbital position(s) as criteria request.

**Comment by sofia-tsa** [comment]
How should the orbital position be used? There is no orbital position query parameter in the CSR query API

**Comment by paulhiggs** [comment]
Im not sure is any of the DVB NIP team are active in this repository - perhaps you need to contact directly the TM-NIP team

**Comment by juhajoki** [comment]
completed
