### ISSUE TITLE
Migrating the existing Android implementation to APK to support native code

### ISSUE THREAD

**Issue by juhajoki** [DVBProject/DVB-I-Reference-Client#108]

**Comment by sofia-tsa** [comment]
APK wrapper added in f237375aef536d8b71cd02c04d95e9572535fc24

**Comment by paulhiggs** [comment]
the `frontend\android_apk\README.md` seems to contain a lot of old/boilerplate information.

Can you clean it up and include some instructions on how to build the APK (I presume using gradle)

**Comment by juhajoki** [comment]
yes, readme in placeholder mode now. @sofia-tsa to write proper notes.

**Comment by sofia-tsa** [comment]
Readme updated both the one in the frontend/android_apk and root readme. Added link to the APK

**Comment by jpiesing** [comment]
> Readme updated both the one in the frontend/android_apk and root readme. Added link to the APK

The root readme contains old information about the PWA ...

![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/8490792/40a981ae-9fb6-43e4-ad9c-95ac3c812114)

and

![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/8490792/bd95b20d-1f14-4f09-83c0-a9ea3522762b)

I think you need to merge the two references to Android to explain that there are two choices available and when to use each.

**Comment by paulhiggs** [comment]
When I use the `frontend_apk\gradlew.bat`, there is a error related to the installation process...
````
PS D:\Documents\dvb\DVB-I-Reference-Client (github)\frontend\android_apk> ./gradlew.bat
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.For more details on the daemon, please refer to https://docs.gradle.org/8.7/userguide/gradle_daemon.html in the Gradle documentation.
Process command line: C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot\bin\java.exe -XX:MaxPermSize=512m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp C:\Users\p00555659\.gradle\wrapper\dists\gradle-8.7-bin\624l31j1ldat0j4r6dari2ed3m\gradle-8.7\lib\gradle-launcher-8.7.jar -javaagent:C:\Users\p00555659\.gradle\wrapper\dists\gradle-8.7-bin\624l31j1ldat0j4r6dari2ed3m\gradle-8.7\lib\agents\gradle-instrumentation-agent-8.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.7
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
````

I am using [Java 21.0.3.9 from Eclipse Adoptum](https://adoptium.net/en-GB/temurin/releases/) and tracking down the "MaxPermSize=512m" yields some ideas

https://stackoverflow.com/questions/47112412/unrecognized-vm-option-maxpermsize-512m-when-running-zeppelin

> It appears the MaxPermSize VM option is no longer supported in Java 9. Perhaps they changed the parameter name or something. 

https://forums.oracle.com/ords/apexds/post/getting-the-error-message-unrecognized-vm-option-maxpermsiz-8238

> Starting OpenJDK17 these java options ‘-XX:MaxPermSize=256m' have been removed and using them results in an error. need to removed ‘-XX:MaxPermSize=512m' in java option and replace with '-XX:MaxMetaspaceSize=512m’.
> Sources:
> https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options

**Comment by lasse-soininen** [comment]
@paulhiggs MaxPermSize issue is fixed as suggested https://github.com/DVBProject/DVB-I-Reference-Client/commit/7c97f3740375759bb84ac8147e6b99e6e64a8f66

**Comment by juhajoki** [comment]
completed, APK available and documented
