### ISSUE TITLE
No RegionList in example service list

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#13]
Since the example service list contains `<TargetRegion>FIN</TargetRegion>` for the <LCNTable> there should also be `<Region countryCodes="FIN" regionID="FIN">`

**Comment by sofia-tsa** [comment]
Perhaps for now the best option wold be to remove the target region from the example service list? 
The example service list is pretty much global so it doesn't really need or use the TargetRegion for anything yet.

We will add the TargetRegion back to the example service list when the region selection is implemented.

**Comment by paulhiggs** [comment]
Yes,  removing the <TargetRegion> from the LCN table would make it applicable "anywhere" and also put in semantic compliance with the specification.

**Comment by paulhiggs** [comment]
No <TargetRegion> in service list
