### ISSUE TITLE
visually distinguish scanned services not in the service list

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#14]
(per the DVB TM_I call on March 3) 
Services which are scanned but are not included in the service list are add as "high channel numbers" in the UI. These should also be shown in a visually different colour and/or have an "!" or "*" appended.

**Comment by paulhiggs** [comment]
These need to be shown to have a "special handling" in the reference client

**Comment by sofia-tsa** [comment]
Fixed in 204fe91
