### ISSUE TITLE
Incorrect value for Service List Logo

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#15]
The HowRelated@href value for a service list logo should be `urn:dvb:metadata:cs:HowRelatedCS:2019:1001.1` according to the defintiion of the HowRelatedCS
example service list has 
``` 
   <RelatedMaterial>
      <tva:HowRelated href="urn:dvb:metadata:cs:HowRelatedCS:2019:1001.2"/>
      <tva:MediaLocator>
        <tva:MediaUri contentType="image/png">https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/channel_icons/chicon_harmonic.png</tva:MediaUri>
      </tva:MediaLocator>
    </RelatedMaterial>```

**Comment by paulhiggs** [comment]
tested against my service list validator
`http://paulhiggs.ddns.net:3010/check?SLurl=https://raw.githubusercontent.com/DVBproject/DVB-I-Reference-Client/master/backend/servicelists/example.xml`

**Comment by sofia-tsa** [comment]
They are meant to be service logos (clause 5.2.6.2), not service list logos (clause 5.2.6.1).
I assumed that service list logos would be used in the `RelatedMaterial`-elements in the `ServiceList`-element and they would be displayed when selecting the service list.

**Comment by paulhiggs** [comment]
Looks like a problem with my XML parser...
