### ISSUE TITLE
Low Latency settings for dash.js player

### ISSUE THREAD

**Issue by sofia-tsa** [DVBproject/DVB-I-Reference-Client#16]
Dash.js has several low latency settings that can be configured as seen in 
http://reference.dashif.org/dash.js/v3.0.0/samples/low-latency/index.html

Should we implement a settings screen in the Android reference app to control those settings or should the reference application use standard low latency settings for playing all the DASH-streams?

**Comment by paulhiggs** [comment]
On the Android client this would be useful - not sure how the setCatchUpPlaybackRate() would work on an HbbTV app, but could be an interesting for testing

**Comment by jpiesing** [comment]
> On the Android client this would be useful - not sure how the setCatchUpPlaybackRate() would work on an HbbTV app, but could be an interesting for testing

It's not usable for HbbTV except if dash.js was being used rather than the built-in player (one of the phase 2 features). It would be useful for that.

**Comment by paulhiggs** [comment]
I think it makes some sense to add the maximum playback rate control.

**Comment by sofia-tsa** [comment]
Release 2.1 includes settings for Dash.js low latency parameters target latency, minimum drift, and cachup playback rate in the Android client
