### ISSUE TITLE
EPG should be available before a service is selected

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#17]
When opening the app on Android, the "EPG" button is not available until a service is selected.
It should be possible to open the EPG in order to select the first service to view.
![no DVB-I epg](https://user-images.githubusercontent.com/3158807/76222029-e5f18c00-6211-11ea-85bd-630bca448773.jpg)

**Comment by sofia-tsa** [comment]
Implemented in relase 2.1
