### ISSUE TITLE
setting priority for dash and dvb-T

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#18]
I added a new service as dash and dvb-t to the service list. you can see it as example-irib in Sofia dvb service list generator.  I am using the latest published version of the client on my webserver.
in hbbtv mood, TV  launches DVB-T  when I set higher priority for dash.

**Comment by paulhiggs** [comment]
Looking at your service list, http://77.36.157.4/h3/test/DVB-I-Reference-Client-master/backend/servicelist.php, the DASH service instance has priority=2 and the DVB-T service instance has priority=1 (note that the order of <ServiceInstance> elements is inconsequential.
````
<Service version="1">
 <UniqueIdentifier>sid15</UniqueIdentifier>
 <ServiceInstance priority="2">
  <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
  <DASHDeliveryParameters>
   <UriBasedLocation contentType="application/dash+xml">
    <URI>
     http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd
    </URI>
   </UriBasedLocation>
  </DASHDeliveryParameters>
 </ServiceInstance>
 <ServiceInstance priority="1">
  <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
  <DVBTDeliveryParameters>
   <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
   <TargetCountry>IRN</TargetCountry>
  </DVBTDeliveryParameters>
 </ServiceInstance>
 <ServiceName>IRIB1</ServiceName>
 <ProviderName>IRIB</ProviderName>
</Service>
````

The description of `ServiceInstance` in Table 13 of [A177](https://dvb.org/wp-content/uploads/2019/11/A177_DVB-I_Nov_2019.pdf) states 

> The instances(s) where the A/V content for the service may be found. If multiple elements of this type are present and available (refer to clause 5.2.5), the one with the lowest value of the `@priority` attribute has the highest priority. All ServiceInstances for a given Service carry the same editorial content.

In this case, the client should select the dvb-t service instance.

**Comment by ffallahi6303** [comment]
Hi, As I am testing the service , I had changed it. now I changed priority as you mentioned. 
</Service>
  <Service version="1">
  <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
    </ServiceInstance>
    <UniqueIdentifier>sid15</UniqueIdentifier>
        <ServiceInstance priority="2">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
         <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
        <TargetCountry>IRN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
	
    <ServiceName>IRIB1</ServiceName>
    <ProviderName>DVB</ProviderName>
      </Service>

still TV just show DVB-T not DVB-Dash.

**Comment by ffallahi6303** [comment]
I set the priority as you mentioned. still, TV shows just DVB-T not DVB-Dash
<Service version="1">
   <UniqueIdentifier>sid15</UniqueIdentifier>
  <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
    </ServiceInstance>
           <ServiceInstance priority="2">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
         <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
        <TargetCountry>IRN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
	
    <ServiceName>IRIB1</ServiceName>
    <ProviderName>DVB</ProviderName>

**Comment by ffallahi6303** [comment]
`<Service version="1">
   <UniqueIdentifier>sid15</UniqueIdentifier>
  <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
    </ServiceInstance>
           <ServiceInstance priority="2">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
         <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
        <TargetCountry>IRN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
	
    <ServiceName>IRIB1</ServiceName>
    <ProviderName>DVB</ProviderName>`

**Comment by ffallahi6303** [comment]
I set the priority as you mentioned. still, TV shows just DVB-T not DVB-Dash
I set the priority as you mentioned. still, TV shows just DVB-T not DVB-Dash
I set the priority as you mentioned but still TV shows DVB-T.

<Service version="1">
   <UniqueIdentifier>sid15</UniqueIdentifier>
  <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
    </ServiceInstance>
           <ServiceInstance priority="2">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
         <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
        <TargetCountry>IRN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
	
    <ServiceName>IRIB1</ServiceName>
    <ProviderName>DVB</ProviderName>
      </Service>

**Comment by ffallahi6303** [comment]
`<Service version="1">
   <UniqueIdentifier>sid15</UniqueIdentifier>
  <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
    </ServiceInstance>
           <ServiceInstance priority="2">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
         <DVBTriplet origNetId="3622" tsId="101" serviceId="101"/>
        <TargetCountry>IRN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
	
    <ServiceName>IRIB1</ServiceName>
    <ProviderName>DVB</ProviderName>
      </Service>`

**Comment by paulhiggs** [comment]
Can you make a test whereby the service only contains a DVB DASH service instance and advise if that is working? You could do this either by modifying the sid15 service or by creating another (i.e. `UniqueIdentifier>sid15new</UniqueIdentifier>` and adding this to the LCN list
````
<Service version="1">
 <UniqueIdentifier>sid15new</UniqueIdentifier>
 <ServiceInstance priority="2">
  <SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
  <DASHDeliveryParameters>
   <UriBasedLocation contentType="application/dash+xml">
    <URI>
     http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd
    </URI>
   </UriBasedLocation>
  </DASHDeliveryParameters>
 </ServiceInstance>
<ServiceName>IRIB1</ServiceName>
 <ProviderName>IRIB</ProviderName>
</Service>
````

**Comment by ffallahi6303** [comment]
yes, I have done it. Tv shows it correctly if I set it only  as dash service.

**Comment by ffallahi6303** [comment]
even I had a test that I added two services and SID, one DVB and one dash. no problem . just when I add two service instances with priority, TV just shows DVB-T.

**Comment by sofia-tsa** [comment]
Service priorities are not yet implemented in the reference client

**Comment by paulhiggs** [comment]
Lets keep this issue open for now  - I dont see anything specific to this in the phase 1 or 2 work items, neither the use of @priority in the initial instance selection or in some automatic "switchover" handling

**Comment by sofia-tsa** [comment]
Should be quite straightforward to select the highest priority service instance at startup or service selection, I'll try to implement it as soon as I can.

**Comment by sofia-tsa** [comment]
Selecting highes priority service instance implemented in b8c23ef02578038b394e1b3d3cf917dfc0e548e8

**Comment by paulhiggs** [comment]
Thanks Tomi.
You might have noticed that in the specification update that we are working on, the <SourceType> element has been deprecated and made optional. It did not serve any meaningful purpose when the type of source for the service instance could be deduced from the existance of the <xxxxDeliveryParameters>, i.e. if a service instance conatins <DVBCDeliveryParameters> then that instance has a source type of DVB-C. 
Removing this element also alleviates an anomoly whereby a service instance could be defined as source:dvb-t but then contain <DVBSDeliveryParameters>.

It may be useful to look into such an algorithmic determination of the source type for a service instance in future updates

**Comment by sofia-tsa** [comment]
Ok, I have missed that change but makes sense. Should be simple to change the client to determine the source type by the deliveryparameter element. Updating the example service list and the service list needs to done too but I'll do that after update is official.

**Comment by paulhiggs** [comment]
Seems that selecting the highest priority service instance has now been resolved
