### ISSUE TITLE
Adding AIT to the dash service

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#19]
Does the client support hbbtv application for a dash service? 

I added AIT to a dash service but now the service list isn't displayed on the TV. 

  ```
<Service version="1">
<UniqueIdentifier>sid15</UniqueIdentifier>
<ServiceInstance priority="1">
<SourceType>urn:dvb:metadata:source:dvb-dash</SourceType>
<DASHDeliveryParameters>
<UriBasedLocation contentType="application/dash+xml">
<URI>
http://test.livemedia.irib.ir/mdash/tv1-1m.stream/manifest.mpd
</URI>
</UriBasedLocation>
</DASHDeliveryParameters>
<RelatedMaterial xsi:type="tva2:ExtendedRelatedMaterialType">
<HowRelated href="urn:dvb:dvbi:cs:LinkedApplicationCS:2019:1.1"/>
<MediaLocator>
<MediaUri/>
<AuxiliaryURI contentType="application/vnd.dvb.ait+xml"> https://tv-html.irt.de/hbbtv/dvbi/xml.aitx </AuxiliaryURI>
</MediaLocator>
</RelatedMaterial>
</ServiceInstance>
<ServiceName>IRIB1</ServiceName>
<ProviderName>IRIB</ProviderName>
</Service>
```

**Comment by jpiesing** [comment]
> Does the client support hbbtv application for a dash service?

Not yet. It's in the list for phase 2 but work on phase 2 has only just started.

**Comment by paulhiggs** [comment]
As a clarification, the phase 1 work was intended to showcase some basic aspects for the DVB World event in March. As signalling and launching applications if not really "basic" it is in phase 2 which is intended to be complete to demonstrate at IBC in September

**Comment by paulhiggs** [comment]
I also do not understand why you use `xsi:type="tva2:ExtendedRelatedMaterialType"` for the `<RelatedMaterial>` element. All the necessary elements are defined in `tva:RelatedMaterialType` and DVB-I makes no use of TVA-2 datatypes.

This seems to be a 'remnant' from a FVP idea of using something from ExtendedRelatedMaterialType but in reality, this is not done

**Comment by ffallahi6303** [comment]
> I also do not understand why you use `xsi:type="tva2:ExtendedRelatedMaterialType"` for the `<RelatedMaterial>` element. All the necessary elements are defined in `tva:RelatedMaterialType` and DVB-I makes no use of TVA-2 datatypes.
> 
> This seems to be a 'remnant' from a FVP idea of using something from ExtendedRelatedMaterialType but in reality, this is not done

yes, I received this format from IRT last year, and I think I should correct it. just I wonder if I can use AIT as a related material for a service with only DVB service instance? if yes, it would be so good as it helps me to add hbbtv application to all broadcast services, too.

**Comment by paulhiggs** [comment]
Launching of apps signaled in the service list is now implemented
