### ISSUE TITLE
Unable to delete new service list

### ISSUE THREAD

**Issue by wschidol** [DVBproject/DVB-I-Reference-Client#2]
In the Sofia hosted backend, I created a new service list ("my first service list.xml"). Using the "delete" button on the list brings up an error message:
![image](https://user-images.githubusercontent.com/36198156/74150539-6c628000-4c0a-11ea-8dab-8d8b9fce7213.png)

**Comment by sofia-tsa** [comment]
Deleting servicelists is  not implemented yet, will be added in the next update

**Comment by sofia-tsa** [comment]
Deleting servicelists implemented

**Comment by wschidol** [comment]
I can confirm that deletion works now.
