### ISSUE TITLE
changing the UI language

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#22]
I added Farsi in language setting. create fa.json  but changing the language just changes ( "epg_button" and "settings" words)  not others for example audio language and...

`{
"settings":"تنظیمات",
"parental_block":"محتوا مناسب سن کودکان نیست",
"epg_button":"راهنمای برنامه",
"subtitle_button":"زیرنویس",
"audio_button":"صدا",
"close_button":"بستن"
}
`
i checked fin too, we have more words in [fi.json](https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/i18n/fi.json) but just these two words would be changed by selecting suomi.

**Comment by ffallahi6303** [comment]
i think just main buttons have been defined for changing by UI language.

**Comment by ffallahi6303** [comment]
I updated  [i18n.js](https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/i18n/i18n.js)  and [en.json](https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/i18n/en.json)  and [player.html](https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/android/player.html)
now all text can be translated.





`

**Comment by ffallahi6303** [comment]
en.json
`{
"settings":"Settings",
"parental_block":"Content blocked by parental control",
"epg_button":"Open EPG",
"subtitle_button":"Subtitles",
"audio_button":"Audio",
"close_button":"Close",
"Tune":"Tune Channel",
"Video_resolution":"Video resolution",
"Video_bitrate":"Video bitrate",
"Audio_bitrate":"Audio bitrate",
"Latency":"Latency",
"Parental_settings":"Parental settings",
"Language_settings":"Language settings",
"Select_servicelist":"Select servicelist",
"stream_info":"stream info",
"LL_settings":"Low latency settings",
"LL_mode":"Low latency mode",
"LL_target":"Target latency:",
"min_drift":"Minimum drift (seconds):",
"Catchup_rate":"Catch-up playback rate (%):",
"min_age":"minimum age",
"provider":"provider",
"language":"language",
"Genre":"Genre",
"country":"Country",
"Regulator_list":"Regulator list",
"filter":"filter"
}`

Fa.json
`{
"settings":"تنظیمات",
"parental_block":"محتوای نامناسب برای همه سنین",
"epg_button":"راهنمای برنامه الکترونیک",
"subtitle_button":"زیرنویس",
"audio_button":"صدا",
"close_button":"بستن",
"Tune":"تماشای شبکه",
"Video_resolution":"رزلوشن ویدئو",
"Audio_bitrate":"نرخ بیت صدا",
"Video_bitrate":"نرخ بیت ویدئو",
"Latency":"تاخیر",
"Parental_settings":"تنظیمات رده بندی سنی",
"Language_settings":"تنظیمات زبان",
"Select_servicelist":"انتخاب لیست سرویس",
"stream_info":"اطلاعات استریم",
"LL_settings":"تنظیمات تاخیر",
"LL_mode":"مود تاخیر",
"LL_target":"تاخیر هدف:",
"min_drift":"حداقل دریفت(ثانیه) :",
"Catchup_rate":"سرعت مرور فیلم (%):",
"min_age":"حداقل سن",
"provider":"تامین کننده",
"language":"زبان",
"Genre":"ژانر",
"country":"کشور",
"Regulator_list":"لیست رگولاتور",
"filter":"فیلتر"
}`

**Comment by sofia-tsa** [comment]
Thank you, I'll add those translations to the main codebase soon.
The localization is a work in progress, i'll update all the UI texts to localized versions  as soon as I have the time, also in the HbbTV client. 
I will also write a guide on how to add languages to the localization. I'll need to think of a way to add a localization language to the app just by adding the localization json-file without having to list the language in the i18n.js-file.

**Comment by ffallahi6303** [comment]
> Thank you, I'll add those translations to the main codebase soon.
> The localization is a work in progress, i'll update all the UI texts to localized versions as soon as I have the time, also in the HbbTV client.
> I will also write a guide on how to add languages to the localization. I'll need to think of a way to add a localization language to the app just by adding the localization json-file without having to list the language in the i18n.js-file.

I sent i18n.js and player.html, too.
Just with replacing these files with ones in main code, atleast all UI text will be accessible for translation.

Now I updated my local client with them and they are working.
