### ISSUE TITLE
a problem in info displaying

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#23]
.
by pressing the blue button on RC of TV (HbbTV), we should have info of the program. it displays wrong . upper and middle of the screen

also still there is no button for EPG and info and setting on the screen for hbbtv. of course blue, yellow and green buttons have been assigned.

**Comment by paulhiggs** [comment]
Could you take a picture of what you are seeing and add it to this issue

**Comment by sofia-tsa** [comment]
The program info layout is a CSS issue, will be fixed asap.

**Comment by sofia-tsa** [comment]
Fixed in release 2.9, please verify

**Comment by ffallahi6303** [comment]
now it is showing correctly, Thank you.
