### ISSUE TITLE
not palying a local dash stream

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#24]
Hello, I think this question is not directly related to the this client and project but I hope you can help me with it:

I have a dash stream :  http://livemedia2.irib.ir/mdash/aflak-300k.stream/manifest.mpd
dash reference client 3.1.1  plays it but DVB-I client doesn't  and I can't understand the problem. 

Can you help me , please?

**Comment by jpiesing** [comment]
Is the DVB-I client loaded by https? If so then there might be a mixed content effect happening?
Do you have a TV supporting W3C MSE in HbbTV mode? If so, does the DVB-I client still not play it if you switch from using the native player to MSE or vice-versa?

**Comment by ffallahi6303** [comment]
Thank you , I used new version of application and all are working well, now.  I had two other dvb-I client apps on my phone and I think that it caused some confusing as service list couldn't be updated in application correctly.  Also I think our dvb dash server should be checked for stability, too.
