### ISSUE TITLE
DVB-I for radio channels

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#26]
Is it possible to have a service list of radio channels and offering it via DVB-I?

**Comment by paulhiggs** [comment]
Yes, there are a couple of aspects to consider 

- The <AVAttributes> should only have an <AudioAttribites> and not <VideoAttribites>

See Table 65 for how broadcast service types (including radio) should be mapped onto DVB-I XML

**Comment by paulhiggs** [comment]
In [DVB DASH](https://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.03.01_60/ts_103285v010301p.pdf) it is possible to define an MPD that only contains "audio" Adaptation Sets, in such cases the AVAttribites for the `<ServiceInstance>` would only include audio definition(s).

A168 does permit images and text (see clause 9.1.7) to be visually presented when they are signaled as inband events, but I am not sure if dash.js looks at 'radiovis' events.

Ideally we should have a DVB reference stream with these events included - will follow up with the DVB TM-STREAM group
