### ISSUE TITLE
mini epg

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#27]
Hello,
in information field related to the channel, we have some information related to the now and next program. I can't find the functions related to this part in the code. can you help me to find it? I need to make some changes to it for localization.

**Comment by sofia-tsa** [comment]
Hi,

TVAnytime document parsing can be found in https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/channel-common.js , parseSchedule-function. It is used for parsing the now/next information and schedule information.

**Comment by ffallahi6303** [comment]
thank you . I did.
