### ISSUE TITLE
Support of HLS

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#28]
I know in dvb-I we should support dash but i wonder if we can use HLS stream as in some where dash is not prepared?

**Comment by paulhiggs** [comment]
The DVB-I Reference Client supports DVB-DASH (A168) service instances.

The latest [A177r1 update](https://dvb.org/?standard=service-discovery-and-programme-metadata-for-dvb-i) (published on 20 July 2020) allows for a user-defined delivery parameters type to be used for a service instance. Any values signaled in this type would be passed to the appropriate player.

**Comment by paulhiggs** [comment]
Closing this issuse - DVB will not likely define elements for non-DVB delivery mechanisms

**Comment by paulhiggs** [comment]
Here is how you could use the `<OtherDeliveryParameters>` element that is now in the `<ServiceInstance>`

First, define a schema that contains the sub-elements you want, deriving the type from `dvbisd:ExtensionBaseType`
````
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"targetNamespace="urn:paulhiggs:HLSdelivery:2020" xmlns:dvbisd="urn:dvb:metadata:servicediscovery:2020"elementFormDefault="qualified" attributeFormDefault="unqualified">
      <import namespace="urn:dvb:metadata:servicediscovery:2020"schemaLocation="../dvbi_v2.0.xsd"/>
     
      <complexType name="HLSDeliveryParametersType">
             <complexContent>
                   <extension base="dvbisd:ExtensionBaseType" extensionName="PH-HLS.0">
                          <sequence>
                                <element name="HLSDUrl"type="dvbisd:ExtendedURIType"/>
                          </sequence>
                   </extension>
             </complexContent>
      </complexType>
</schema>
```` 

Then use it in your service instance
````
 <ServiceInstance priority="1">
  <DisplayName>Rai 3 TGR Lombardia</DisplayName>
  <OtherDeliveryParameters xsi:type="HLSDeliveryParametersType">
   <HLSUrl contentType="application/vnd.apple.mpegurl">
    <URI>
      https://pauls.net/live-channels/ch1/playlist.m3u8
    </URI>
   </HLSUrl>
  </OtherDeliveryParameters>
 </ServiceInstance>
````
