### ISSUE TITLE
IRT subtitle channel on Android

### ISSUE THREAD

**Issue by jpiesing** [DVBproject/DVB-I-Reference-Client#3]
The IRT subtitle channel on Android doesn't show subtitles.
Either it should be renamed or the subtitles should be shown.
I believe dash.js supports showing TTML/IMSC subtitles using a JavaScript renderer.

**Comment by paulhiggs** [comment]
The MPD indicates that multiple subtitles are available for this service
`
     <AdaptationSet contentType="text" lang="eng" mimeType="application/mp4" segmentAlignment="true">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle" />
         <SegmentTemplate duration="2" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="0" />
         <Representation bandwidth="5367" codecs="stpp" id="sub_eng" startWithSAP="1" />
      </AdaptationSet>
      <AdaptationSet contentType="text" lang="eng" mimeType="application/mp4" segmentAlignment="true">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="caption" />
         <SegmentTemplate duration="2" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="0" />
         <Representation bandwidth="5367" codecs="stpp" id="sub_eng_cap" startWithSAP="1" />
      </AdaptationSet>
      <AdaptationSet contentType="text" lang="swe" mimeType="application/mp4" segmentAlignment="true">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle" />
         <SegmentTemplate duration="2" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="0" />
         <Representation bandwidth="5367" codecs="stpp" id="sub_swe" startWithSAP="1" />
      </AdaptationSet>
      <AdaptationSet contentType="text" lang="qbb" mimeType="application/mp4" segmentAlignment="true">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle" />
         <SegmentTemplate duration="2" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="0" />
         <Representation bandwidth="5367" codecs="stpp" id="sub_ttml_qbb" startWithSAP="1" />
      </AdaptationSet>
      <AdaptationSet contentType="text" lang="nor" mimeType="application/mp4" segmentAlignment="true">
         <Role schemeIdUri="urn:mpeg:dash:role:2011" value="subtitle" />
         <SegmentTemplate duration="2" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/$Number$.m4s" startNumber="0" />
         <Representation bandwidth="5367" codecs="stpp" id="sub_nor" startWithSAP="1" />
      </AdaptationSet>
`
The RFP seeks subtitle support in Phase 2.

**Comment by juhajoki** [comment]
as Paul said, subtitles will be supported in a future release. Perhaps a documentation issue?

**Comment by jpiesing** [comment]
> as Paul said, subtitles will be supported in a future release. Perhaps a documentation issue?

Then please change the title of the service in the service list until subtitles are supported.
