### ISSUE TITLE
updating the client

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#30]
I have a problem in test of client. I can't see changes in the android and hbbtv client immediately by refreshing the pages after changing in the code. I am testing them by HbbTV viewer on Mozilla and (android phone and also chrome) for android.

I have to close browser, clear history to see the changes.  one of the problem is that after selecting the service list, client uses it and it seems it doesn't update its graphic . I saw in the code that hbbtv client update service list every minute .but not its html.??

now, I have to close browser. clear history and start both clients from the service list selection page to be able to see changes in the client.

**Comment by paulhiggs** [comment]
Normally the application logic (HTML, JS, CSS) does not reload one running, however the application can read supporting data (such as the XML ML

**Comment by paulhiggs** [comment]
No development action needed for this
Closing
