### ISSUE TITLE
removing mini epg from the channel list

### ISSUE THREAD

**Issue by ffallahi6303** [DVBproject/DVB-I-Reference-Client#31]
I need to remove info box from the channel list. as still my epg data is nor prepared then I don't want to display now and next program information and box in the channle list. 

but I can't find related parts in the code. can you please help me with it?

**Comment by paulhiggs** [comment]
It seems all of these items are in the  `<div id="channel_info">` and updated through calls to `Channel.prototype.updateChannelInfo` 

You could comment out these calls (I found three places) and see if that helps

**Comment by ffallahi6303** [comment]
I think it is in Channel.prototype.getNowNext(). actually my question was about disabling this now and next box in menu. 
displaying channel info is by key and I can disable it.

by the way as I removed EPG data from the backend based on the following part in [https://github.com/DVBproject/DVB-I-Reference-Client/blob/master/frontend/hbbtv/launcher/channel.js](url) , just a black image is displayed in one box and text" no program found" .of course I changed the code and related CSS then now it doesn't display any black box or text.

`if(!self.epg || self.epg.length == 0) {
            var placeholder = { text : "" };
            var box = new Box( placeholder, self.element_id + "_" + self.code);
            box.name = self.name;
            box.parentimage = "";
            box.description =  "";
            var now = box;
            var info = "";
            now.info = info;
            self.boxes.push(now);
        }`
 
the result is 
![image](https://user-images.githubusercontent.com/44312423/94336374-a775c000-ffef-11ea-9669-c18f3d78b081.png)

but still I couldn't remove the gap between selected channel( menu[0]) and next channel.


by the way, I think it would be better if all features could be selectable in the client. for example now  displaying epg and info are done by keys. it would be better to displaying these boxes could be selectable, too. in this way, app localization is more easier.

**Comment by paulhiggs** [comment]
It is good to see that the reference code is useful to you, as it is supplied in source format (HTML, CSS and Javascript) it can be adopted to your specific needs.
But please note that DVB is providing this as a reference to show how DVB-I could work and how the service list and content guide metadata can be used. It is not intended to be a reference for a commercial product and any design decisions taken were done to minimize the development cost while increasing the functionality offered. 
Once the contracted development phases are completed, DVB will likely look to the community to continue developing the reference (either in the DVB repository or other forks)
