### ISSUE TITLE
Frontend unclear

### ISSUE THREAD

**Issue by haudiobe** [DVBproject/DVB-I-Reference-Client#32]
I tried the front end for browser and android and it is not very intuitive.

1) it is unclear that you can select some service lists on the right
2) when I select a service list, and then I try stream, several of the streams are not working. There should be a clear message on why the stream is not working.
3) manouvering back and force is unclear. I could not get back to the service list
4) It is unclear how I could enter a service list. What is the format?

**Comment by paulhiggs** [comment]
On item 1, perhaps adding a bullet would help to indicate that the 4 items under "Select Service List" are the service lists

On item 2, it seems that the BR services are not currently working on the "DVB-I Reference Client service list". Is there any signaling from dash.js regarding the retrieval of the MPD or media segments? 
- https://irtdashreference-i.akamaihd.net/dash/live/901161/keepixo1/manifestBR2.mpd could not be retrieved
- https://irtdashreference-i.akamaihd.net/dash/live/901161/keepixo1/manifestBR.mpd could not be retrieved
If dash.js can give a signal, we should just write up "The selected service is not currently available" in the middle of the screen, with the appropriate localization. Additionally, the reference client could make a determination by making a GET on the MPD

On item 3, just a screen tap to get the UI back. Is there any other option on a touch screen device

On item 4, the staging system backend, includes some service lists in the format defined by A177 / TS 103 770. If you want to experiment with your own service lists, then you would need to build your backend using the code available in <backend> directory. Instructions at the bottom of the readme.md

**Comment by haudiobe** [comment]
Ok - maybe someone can file an issue here: https://github.com/Dash-Industry-Forum/dash.js/issues/new/choose

**Comment by dsilhavy** [comment]
Regarding 2. You can listen for errors in the player and show an appropriate error message. In your case something like:

````
            player.on(dashjs.MediaPlayer.events.ERROR, function (e) {
                if (!e.event) {
                    switch (e.error.code) {
                        case dashjs.MediaPlayer.errors.DOWNLOAD_ERROR_ID_MANIFEST_CODE:
                            console.log('manifest error');
                            break;
                        case dashjs.MediaPlayer.errors.DOWNLOAD_ERROR_ID_CONTENT_CODE:
                            console.log('segment error');
                            break;
                    }
                }
            });
````

**Comment by paulhiggs** [comment]
At some stage it would be nice to have a more mobile centric front-end, perhaps with tiles containing the service logos and dropping the LCN numbers (but possibly ordered by LCN number in the background)

Mobile devices could completely ignore the LCN Table and just add services that have a playable service instance

**Comment by paulhiggs** [comment]
> On item 2, it seems that the BR services are not currently working on the "DVB-I Reference Client service list". Is there any signaling from dash.js regarding the retrieval of the MPD or media segments?
> 
> * https://irtdashreference-i.akamaihd.net/dash/live/901161/keepixo1/manifestBR2.mpd could not be retrieved
> * https://irtdashreference-i.akamaihd.net/dash/live/901161/keepixo1/manifestBR.mpd could not be retrieved
>   If dash.js can give a signal, we should just write up "The selected service is not currently available" in the middle of the screen, with the appropriate localization. Additionally, the reference client could make a determination by making a GET on the MPD
> 

When a stream cannot an error message is now displayed
![2020-12-15 09 55 11](https://user-images.githubusercontent.com/3158807/102199749-e2371800-3ebb-11eb-9625-2c3d693421c5.jpg)

**Comment by jpiesing** [comment]
If the MPD cannot be fetched then an error message like "stream not available" might be more intuitive.

**Comment by paulhiggs** [comment]
> I tried the front end for browser and android and it is not very intuitive.
> 
> 1. it is unclear that you can select some service lists on the right
> 3. manouvering back and force is unclear. I could not get back to the service list

These are some "UI Design choices" that were made in the reference app which may differ from expectations or typical commercial use. Full source is provided to allow experimentation and customixation

> 4. It is unclear how I could enter a service list. What is the format?
Service List XML is according to TS 103 770.

**Comment by paulhiggs** [comment]
We will discuss mobile UI aspects in upcoming PCM to ensure we have a client that meets expectations for promoting DVB-I on mobile devices. How such improvements will be implemented is to be determined
