### ISSUE TITLE
UI localisation should use 2 character language codes

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#36]
In A177 we have tried to follow the intent of [BCP 47: Tags for Identifying Languages](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) and only used 2 character codes throughout

The `i18n.js` uses "eng" for English, "fin" for Finish and "zhn" for Chinese, but according to the [IANA language registry](www.iana.org/assignments/language-subtag-registry/language-subtag-registry) the 2 character codes for these are en, fi and zh

**Comment by jpiesing** [comment]
This subject is a recurring source of pain. 
HTML5 is BCP47. 
DASH follows RFC5646 which is another name for BCP47.
"When languages have both an ISO 639-1 two-character code and a three-character code (assigned by ISO 639-2, ISO 639-3, or ISO 639-5), only the ISO 639-1 two-character code is defined in the IANA registry."
DVB-SI uses 3-character language codes throughout.

**Comment by sofia-tsa** [comment]
I was approaching this from the HbbTV and broadcast (DVB-SI) side, and they use ISO639-2 3 character language codes.
We can change the UI localization to use 2 letter codes. Just thinking ahead, if we need to display broadcast metadata, then we'll need a lookup table to map the 2 letter codes to 3 letter codes.

**Comment by jpiesing** [comment]
It's not hard to find tables listing the 2 and 3 character codes for languages that have both. Here's one page with a lot of resources. Others exist.
https://datahub.io/core/language-codes
This looks like it might be the most useful of the resources from that page.
https://datahub.io/core/language-codes/r/language-codes-3b2.json

**Comment by paulhiggs** [comment]
I was thinking of just adding alias values to the current I18n class, i.e. change
````
this.languages = [{"lang":"eng","name":"English"},{"lang":"fin","name":"Suomi"},{"lang":"zhn","name":"Chinese"}];
````
to
````
this.languages = [{"lang":"en","name":"English", "alias":["eng"]},{"lang":"fi","name":"Suomi":"alias":["fin"]},{"lang":"zh","name":"Chinese", "alias":["zhn"]}];
````

with some appropriate changes to the class methods. Should be enough for the Reference implementation.

I was experiementing with adding some `<Title xml:lang="zh"` elements in the sample EPG metadata and they were not showing up...

**Comment by paulhiggs** [comment]
This patch does several things...

1. changes `lang=` to `xml:lang=` in template EPG metadata files
2. add some Chinese (`xml:lang="zhn"`) descrptions to some EPG metadata
3. adds localizable strings for all UI text elements
4. uses the `xml:lang` definition from ancestor elements when not specified
5. some small changes to keep jshint happy (var -> let; use of semicolons etc)

[0001-additional-localisation.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6684310/0001-additional-localisation.zip)

**Comment by sofia-tsa** [comment]
I'll try to take a look at this as soon as possible. Looking at the notes, number 5 is a problem. HbbTV uses ECMAScript 5 and let is ES6 syntax. In the Android client source let can be used but the common and HbbTV code needs to be ES5 compatible so we need to use var there.

**Comment by sofia-tsa** [comment]
Other option would be to use ES6 (or newer) for all the Javascript source code and then transpile the source to ES5 compatible for HbbTV clients.

**Comment by paulhiggs** [comment]
OK, i can check the let/vat issue. There were a few instances where `var i` etc was used seneral time in one block and also a few other instances where variable names were (confusingly) reused, i.e.
````
var program=
if (program) {
  var program = program.name
}
````
