### ISSUE TITLE
Labelling services

### ISSUE THREAD

**Issue by paulhiggs** [DVBproject/DVB-I-Reference-Client#4]
Even though this is just a reference, can we changed teh displayed name of sid5 from "Akamai Low Latency DASH" to "Akamai Low Latency FFMPEG"

1. All broadband services are DASH anyway, this will help identify the service as being coded through the DASH-IF/DVB FFMPEG update

**Comment by juhajoki** [comment]
will be fixed in next release.
would be good to settle all service names for the demo in the near future.

**Comment by paulhiggs** [comment]
Yes, I only have the mobile client, so I cannot comment on the broadcast service names that will be used in Valencia

**Comment by jpiesing** [comment]
> Yes, I only have the mobile client, so I cannot comment on the broadcast service names that will be used in Valencia

I don't understand the comment - doesn't the mobile client uses the same service names as the broadcast? (I also only have the mobile client).

**Comment by paulhiggs** [comment]
Yes, but if the service does not have a DVB-DASH service instance, then it is not shown on the mobile client. the current service list example has two of these
```
  <Service version="1">
    <UniqueIdentifier>sid1</UniqueIdentifier>
    <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
        <DVBTriplet origNetId="8916" tsId="4097" serviceId="74"/>
        <TargetCountry>FIN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
    <ServiceName>DVB-T channel 1</ServiceName>
    <ProviderName>DVB</ProviderName>
    <ContentGuideServiceRef>cgsid_1</ContentGuideServiceRef>
  </Service>
  <Service version="1">
    <UniqueIdentifier>sid2</UniqueIdentifier>
    <ServiceInstance priority="1">
      <SourceType>urn:dvb:metadata:source:dvb-t</SourceType>
      <DVBTDeliveryParameters>
        <DVBTriplet origNetId="8916" tsId="4097" serviceId="62"/>
        <TargetCountry>FIN</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
    <ServiceName>DVB-T channel 2</ServiceName>
    <ProviderName>DVB</ProviderName>
    <ContentGuideServiceRef>cgsid_2</ContentGuideServiceRef>
  </Service>
```

**Comment by juhajoki** [comment]
Yes, we have three kinds of services in the service list (non-technically)
1. DASH only
2. DVB only
3. DASH and DVB

and then DVB services that are not listed in the service list. 
We can agree on the first three ones. Category 2 won't show up in android client. The service list itself is the same for all clients.
