### ISSUE TITLE
Missing EPG images are completed by older images

### ISSUE THREAD

**Issue by removogel** [DVBProject/DVB-I-Reference-Client#42]
Android/Web client - If an EPG image is missing, then an old image is displayed.
It can happen that only a part of the entries is provided with EPG images. 
Reproduction
Step 1) The client calls an EPG entry A including image. The image is displayed correctly. 
Step 2) The client now calls an EPG entry B without image. The image of A is shown again although the client has loaded empty.png. 

![image](https://user-images.githubusercontent.com/8896037/146942779-fae3631e-9d4e-4f5c-b034-fe36f140f639.png)

**Comment by paulhiggs** [comment]
The information from the browser console suggests that empty.png was loaded OK (status=200)- the file is small (1.4kB). 

Can you clarify what you mean by 'EPG entry B without image', perhaps attaching the XML fragment and `empty.png` file will help reproduce this
