### ISSUE TITLE
Missing implementation of ProgramInformation.BasicDescription <Synopsis length="long">

### ISSUE THREAD

**Issue by removogel** [DVBProject/DVB-I-Reference-Client#43]
6.10.5.3 ProgramInformation.BasicDescription Element [Detailed Programme Information] describes a long synopsis of 1200 characters.

The client seems to ignore the long synopsis. The presentation of long synopsis would be very helpful for testing.

The sample EPG data synopses with lengths exceeding 400 characters (but the limit is 200)
https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/schedule.php?sids[]=cgsid_9&start=1640041200&end=1640127600

`<Title type="main">We Bought a Zoo</Title>
<Synopsis length="medium">Following his wife's untimely death, Los Angeles journalist Benjamin Mee (Matt Damon) decides to make a fresh start by quitting his job and moving his children (Colin Ford, Maggie Elizabeth Jones) to an 18-acre property containing the Rosemoor Wildlife Park. Though closed for years, Rosemoor is still home to many animals, cared for by Kelly Foster (Scarlett Johansson) and her small staff. Mee opens his heart and his checkbook as he, Kelly and the others work to renovate and reopen the zoo.</Synopsis>`

**Comment by paulhiggs** [comment]
Note that according to [A177r2](https://dvb.org/wp-content/uploads/2020/11/A177r2_Service-Discovery-and-Programme-Metadata-for-DVB-I_ts_103-770-v120_June-2021.pdf), Synposis@length=long is only applicable to Detailed Programme Information (cause 6.10.5.3)

**Comment by removogel** [comment]
Thanks Paul for the quick response. Do I understand correctly - there is no displaying of Detailed Programme Information in the reference client intended?
