### ISSUE TITLE
[Frontend hbbtv] Cannot start a Broadcast related parallel application

### ISSUE THREAD

**Issue by bpeexc** [DVBProject/DVB-I-Reference-Client#44]
Hi,

I wish to start a "Broadcast related" application (with `<HowRelated href="urn:dvb:metadata:cs:LinkedApplicationCS:2019:1.1" />` tag) with your DVB-I hbbtv implementation.
When I make a try, my application is succesfully launched, but I lose my broadcast.

By analyzing your code, parallel "Broadcast related" application seems to be supported :

```
      if(serviceInstance.parallelApps) {
        for(var i = 0;i< serviceInstance.parallelApps.length;i++ ) {
          if(serviceInstance.parallelApps[i].contentType == "application/vnd.dvb.ait+xml") {
            serviceApp = _application_.createApplication(serviceInstance.parallelApps[i].url,true);
            return;
          }
        }
      }
      if(selectedService.parallelApps) {
        for(var i = 0;i< selectedService.parallelApps.length;i++ ) {
          if(selectedService.parallelApps[i].contentType == "application/vnd.dvb.ait+xml") {
            serviceApp = _application_.createApplication(selectedService.parallelApps[i].url,true);
            return;
          }
        }
      }
```
I note you used createApplication HbbTV API function.
But from HbbTV specification, createApplication function is dedicated to "broadcast independent" application.

Did i misunderstand something ?
Is there a limit due to dvb-i implementation in a HbbTV context ?

Below an example of my service list files.

```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceList xmlns="urn:dvb:metadata:servicediscovery:2020" xmlns:mpeg7="urn:tva:mpeg7:2008" xmlns:tva="urn:tva:metadata:2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1" xsi:schemaLocation="urn:dvb:metadata:servicediscovery:2020 dvbi_v2.0.xsd">
  <Name>DVB-I Demo</Name>
  <ProviderName>Demo</ProviderName>
  <LCNTableList>
    <LCNTable>
      <LCN channelNumber="1" serviceRef="tag:dvb.org,2020:sid1"></LCN>
    </LCNTable>
  </LCNTableList>
  <Service version="1">
    <UniqueIdentifier>tag:dvb.org,2020:sid1</UniqueIdentifier>
    <ServiceInstance priority="1">
      <DVBTDeliveryParameters>
        <DVBTriplet origNetId="65281" tsId="1" serviceId="1"/>
        <TargetCountry>FRA</TargetCountry>
      </DVBTDeliveryParameters>
    </ServiceInstance>
    <ServiceInstance priority="2">
      <DASHDeliveryParameters>
        <UriBasedLocation contentType="application/dash+xml">
          <URI>http://my-demo/dash/bbb1/bbb.mpd</URI>
        </UriBasedLocation>
      </DASHDeliveryParameters>
            </ServiceInstance>
    <ServiceName>Channel1</ServiceName>
    <ProviderName>Demo</ProviderName>
    <RelatedMaterial>
      <HowRelated href="urn:dvb:metadata:cs:LinkedApplicationCS:2019:1.1"></HowRelated>
      <MediaLocator>
      <tva:MediaUri contentType="application/vnd.dvb.ait+xml">http://my-demo/dvbi/ait.xml</tva:MediaUri>
      </MediaLocator>
    </RelatedMaterial>
    <ServiceType href="urn:dvb:metadata:cs:ServiceTypeCS:2019:linear"></ServiceType>
    </Service>
</ServiceList>
```

Thanks in advance for your response.

Benjamin

**Comment by sofia-tsa** [comment]
I'm don't think it is even possible to start a broadcast related application without having the application signaled in the broadcast.

DVB-I specification section 5.2.3.3 states:
In the present document, the semantics of applications signalled using a RelatedMaterial element with a
HowRelated@href attribute set to urn:dvb:metadata:cs:LinkedApplicationCS:2019:1.1 are not defined for
broadcast service instances using DVBTDeliveryParameters, DVBSDeliveryParameters or DVBCDeliveryParameters. Such elements should not be used. The DVB-I client shall ignore any application
signalling using a RelatedMaterial element with this HowRelated@href attribute when selecting such a broadcast
service instance and act solely on the broadcast AIT signalling.

Perhaps the reference application should not start the application signaled in RelatedMaterial-element the at all with a DVB-T service.

**Comment by paulhiggs** [comment]
Ideally, and I presume for compatibility with an app environment, an app for a broadcast instance should be signalled in the AIT and launched from there.

The DVB-I specification could be more descriptive in regards to app signalling at the service or instance level, especially of there is application invoked switching of instances.

**Comment by jpiesing** [comment]
The reference app has limitations when run as a regular HbbTV app and lack of support for broadcast-related apps on DVB-I services is one of them. If you run it as an OpApp then these restrictions should go away.

**Comment by juhajoki** [comment]
@bpeexc , do you have access to an environment where you could try running the Reference client in OpApp mode? Exact instructions differ from platform to platform and depending on what kind of equipment you have available.

**Comment by bpeexc** [comment]
Hi,

I'm not sure but I don't think I have an access to an OpApp mode. I use the DVB-I client on mainstream TVs and smartphones.

I finally found a workaround for this issue : I created a broadcast-independant application which embed a DASH player (DashJs).
Like that, if an hybrid TV wants to play a channel in DASH, it will start application defined in AIT with my specifics background services and play dash video on foreground.
Otherwise, others devices just start the DASH video from your DVB-I client with the manifest url defined in the services list.

**Comment by juhajoki** [comment]
ok, good job! To enable OpApp mode even for debugging, you'd need to contact the manufacturer directly. But your solution seems to fit the purpose for now. 
Do you want to share some source code to the project repository here perhaps?

**Comment by bpeexc** [comment]
Below an example of HbbTV application that automatically starts a dash video and does other things

**index.html**
```html
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//HbbTV//1.1.1//EN" "http://www.hbbtv.org/dtd/HbbTV-1.1.1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Launcher</title>
    <meta http-equiv="content-type" content="application/vnd.hbbtv.xhtml+xml; charset=utf-8" />
    <link rel="stylesheet" href="/hbbtv/styles.css" />
</head>
<body>
<script src="/hbbtv/js/main.js"></script>
<div class="App">
    <div id="oipf">
        <object type="application/oipfApplicationManager">
            application/oipfApplicationManager
        </object>
        <object type="application/oipfConfiguration">
            application/oipfConfiguration
        </object>
        <object type="application/oipfCapabilities">
            application/oipfCapabilities
        </object>
    </div>
    <div id="video-container">
        <object type="video/broadcast" aria-label="video/broadcast"></object>
        <video id="video"></video>
    </div>
</div>
</body>
</html>
```

**styles.css**
```css
#oipf {
    visibility: hidden;
    display: none;
}

#video-container object {
    position: absolute;
    top: 0;
    left: 0;
    width: 1280px;
    height: 720px;
    display: block;
    z-index: 0;
}

#video-container video {
    position: absolute;
    top: 0;
    left: 0;
    width: 1280px;
    height: 720px;
    display: block;
    z-index: 0;
}
```

**main.js (using jquery, transpiling with webpack)**
```javascript

import jquery from "jquery"

(function() {

  async function initHbbTV() {
    console.log("Init HbbTV")
    const applicationManager = jquery("#oipf object[type='application/oipfApplicationManager']")[0]

    try {
      const oipfApplication = applicationManager.getOwnerApplication(window.document)
      oipfApplication.show();
    } catch (e) {
      console.log("Non TV Mode")
    }

    const broadcast = jquery("#video-container object[type='video/broadcast']")[0]
    const broadband = jquery("#video")[0]
    return {
      broadcast,
      broadband,
    }
  }

  async function play(broadcast, broadband, url) {
    console.log("prepare Dash")
    let timer
    broadband.setAttribute("src", url)
    const canPlayPromise = new Promise(resolve => {
      broadband.oncanplay = () => {
        console.log("Broadband video can play")
        timer = setTimeout(() => {
          console.log("Force to play broadband")
          resolve()
        }, 1000)
      }
      broadband.oncanplaythrough = () => {
        clearTimeout(timer)
        console.log("Broadband video can play through !")
        resolve()
      }
    })

    return canPlayPromise.then(() => {
      this.__broadcast.stop()
      this.__broadband.play()
    }).catch(e => {
      console.log("Broadcast stop error: " + e.message)
    })
  }

  async function doOtherThings() {
    //TODO
  }
  
  jquery(async () => {
    try {
      const {broadcast, broadband} = await initHbbTV()
      await play(broadcast, broadband, "http://my.dash.example/manifest.mpd")
      await doOtherThings()
    } catch (e) {
      console.log("Error during process: ", e.message)
    }
  })
})()

```

**Comment by juhajoki** [comment]
thanks a lot for this. Just a minor detail, display: none should be avoided. :)
