### ISSUE TITLE
Support of multiple ContentGuides seems to be missing

### ISSUE THREAD

**Issue by removogel** [DVBProject/DVB-I-Reference-Client#45]
For the practical use of DVB-I, distributed content guides are essential. 

In the test, the client cannot resolve the ContentGuide referencing via ContentGuideSourceList & ContentGuideSource. 

It then does not make any requests to the content guide. 

`<ContentGuideSourceList>
<ContentGuideSource CGSID="iSIMS">
<ProviderName>ARD-Playout-Center</ProviderName>
<ScheduleInfoEndpoint contentType="application/xml">
<URI>
http://example.com/dvbi/isims/Senderliste_TV/schedule.php
</URI>
</ScheduleInfoEndpoint>
<ProgramInfoEndpoint contentType="application/xml">
<URI>
http://example.com/dvbi/isims/Senderliste_TV/program.php
</URI>
</ProgramInfoEndpoint>
</ContentGuideSource>
</ContentGuideSourceList>`

later for the service
`<ContentGuideSourceRef>iSIMS</ContentGuideSourceRef>
<ContentGuideServiceRef>eit1.1010.11160</ContentGuideServiceRef>`

**Comment by paulhiggs** [comment]
The DVB-I Reference Client does not use the `<ContentGuideSourceList>` defined in the `<ServiceList>` as such the `ContentGuideSourseRef` is probably not used.
From memory, the reference client uses `<ServiceList><Service><ContentGuideSource>` when it is defined, and `<ServiceList><ContentGuideSource>` as a default for services that do not define their own.
Notes that `ContentGuideSourceList` and `ContentGuideSourceRef` are just an optimization - the same result can be achieved by copying the same `ContentGuideSource` to each `Service`

**Comment by sofia-tsa** [comment]
Paul is correct, the `<ContentGuideSourceList>` and the `<ContentGuideSourceRef>` in a `<Service>` isn't used in the Reference application at the moment. Should this be implemented?

**Comment by hacklsn** [comment]
> Paul is correct, the `<ContentGuideSourceList>` and the `<ContentGuideSourceRef>` in a `<Service>` isn't used in the Reference application at the moment. Should this be implemented?

this would be very helpful in the future, esp. for aggregated service lists
