### ISSUE TITLE
[channel selection] missing channels when TargetRegion element present in <Service>

### ISSUE THREAD

**Issue by hacklsn** [DVBProject/DVB-I-Reference-Client#46]
I've included a TargetRegion Element in each of my Services, e.g.
```
<Service> ....
		<TargetRegion>Deutschland</TargetRegion>
		<ServiceName>Channel name</ServiceName>
		<ProviderName>xxx</ProviderName>
                  ...
</Service>
```
The TargetRegion is of course defined/ listed in the RegionList. 
In channel selection, when i click any specific Region from the Region selection (which is based on LCNtables), most, or even all of the channels are missing from the resulting channel list. The issue is even present if there are no regional LCNTables but only a "global" one (with no LCNTable.TargetRegion). The only way to work around this was to leave out TargetRegion elements completely from the Services.
Service.TargetRegion should not have any effect on channel selection, or if any, narrow down the choice of channels in a regional LCNtable which does not inlude the specific TargetRegion.

**Comment by paulhiggs** [comment]
In DVB-I, the target region selection is an exact match, thus if you have  `<TargetRegion>Deutschland</TargetRegion>` in a service, but select <Region>Brandenburg</Region> then the service **will not** be presented in the UI

**Comment by hacklsn** [comment]
Thanks. I agree that, when selecting subregions of Deutschland, Services targeted at Deutschland can be expected to be excluded.
Even though this poses a problem for multi-national ServiceLists (e.g. satellite), where providers would like to signal a targetCountry (e.g. Turkey, Greece, Italy) but also include subregions below counry level. Probably including all posisible sub-regions in the list of TargetCountries (per service) may solve this? Could you also force service visibility in a subregion by including services into a targeteted LCNTable for the specific sub-region? 
Regionalization and hierarchy is a topic that needs further discussion imo.

In my scenario when selecting Region "Deutschland", only one Service is visible in the channel lsit.
All Services have a TargetRegion element Deutschland.
I would like to ask you to verify this with my (experimental) list for validation
http://dvb-i.bmt-technik.de/demo/targetRegionTest2_2020.xml
