### ISSUE TITLE
Backend for Content Guide does not support URL format from spec

### ISSUE THREAD

**Issue by peterl1000** [DVBProject/DVB-I-Reference-Client#48]
When requesting EPG schedule data for a time range (not now and next), according to the DVB-I spec section 6.5.2.2 the URL format should be:

https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/schedule.php?sid=cgsid_14&start=1651528800&end=1651615200

Note the service ID: **sid=xxx**

However the server only responds when using URL format:

https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/schedule.php?sids[]=cgsid_14&start=1651528800&end=1651615200

Note the service ID: **sids[]=xxx**.

This issue is probably also present in the client.

**Comment by sofia-tsa** [comment]
Reason for this is that the original a177 specification used the sids[]-parameter, r1 and later versions use the sid parameter

**Comment by paulhiggs** [comment]
> Reason for this is that the original a177 specification used the sids[]-parameter, r1 and later versions use the sid parameter

Agreed, but the reference client *should* adhere to [A177r1](https://dvb.org/wp-content/uploads/2019/11/A177r1_Service-Discovery-and-Programme-Metadata-for-DVB-I_July-2020.pdf) / [ETSI TS 103 770 v1.1.1](https://www.etsi.org/deliver/etsi_ts/103700_103799/103770/01.01.01_60/ts_103770v010101p.pdf) which has `sid=`
