### ISSUE TITLE
interaction with Android system UI soft keys

### ISSUE THREAD

**Issue by jpiesing** [DVBproject/DVB-I-Reference-Client#5]
I have installed the PWA on both a phone and a tablet.

The tablet doesn't have any hard buttons / keys at all. The Android system keys for back, home/desktop and the (recently) running apps are all soft keys. Normally they appear at the bottom of the screen & the area used by the app is reduced accordingly. When the DVB-I reference client is running, the 3 soft keys are not shown & the reference app takes over the entire screen. The soft keys are inaccessble & you're basically trapped in the DVB-I reference app. The only thing that can be accessed is the notifications & setttings & if you've got a notification then you can switch to that app & escape.

The phone has the same behaviour (soft keys not shown) but it also has a single hard button that causes the soft keys to be shown as an overlay.

This may be a feature of how PWA apps work but if there's an easy fix, please consider enabling the Android soft keys. If there's not an easy fix then please document it.

**Comment by juhajoki** [comment]
I have a phone with hard keys so I didn't notice this.
The soft keys in Android 10 (following the AndroidOne spec) are accessed by swiping from right. This is a little bit awkard but you are not "trapped" in the app.

**Comment by jpiesing** [comment]
I agree this is my lack of familiarity with a detail of Android.
