### ISSUE TITLE
issue with channel selection when untargeted & targeted LCNTables are present

### ISSUE THREAD

**Issue by hacklsn** [DVBProject/DVB-I-Reference-Client#61]
I have a test service list with 1 untargeted (default) LCNTable as well as 3 targeted LCNTables 
http://dvb-i.bmt-technik.de/demo/bmt_plugfest_2020.xml
After selecting the service list in the SL selection, the UI will present the different regions for choice, but clicking on any region will do nothing.

I have narrowed down the issue. After removing the untargeted LCNTable, there is no issue, so it appears the combination of both is causing issues. 
http://dvb-i.bmt-technik.de/demo/bmt_plugfest_2020_ohne_default_lcn.xml
The issue was not present 2 weeks ago before the latest updates.

**Comment by paulhiggs** [comment]
What should be the user experience when a service list contains both untargeted and region targeted LCN tables?
I can envision a couple of options

1. The untargetted LCN table is ignored and the user must select a region
2. The user selection should include a `default` choice which selects the untargeted LCN table

Option 2 seems like the bets choice and aligns with the specification text "_TargetRegion: If not specified, no regional constraints exist and the LCN table is applicable everywhere._"

**Comment by hacklsn** [comment]
Agreed, option 2 seems like the best choice, esp. for testing purposes. Option 1 is like it was implemented before.
In general, I like to include an untargeted LCNtable as a default incase a device/app does not implement region selection/ there is no match after entering a postcode / user skips region selection.
