### ISSUE TITLE
"Proper OpApp installation techniques will be offered at a later stage. "

### ISSUE THREAD

**Issue by jpiesing** [DVBProject/DVB-I-Reference-Client#66]
The main readme says "Proper OpApp installation techniques will be offered at a later stage. ".

Please can these be offered.

Exactly which files would need to be put in the OpApp .zip file?

**Comment by juhajoki** [comment]
https://github.com/DVBProject/DVB-I-Reference-Client/issues/67

**Comment by juhajoki** [comment]
OpApp instructions and implementation updated
