### ISSUE TITLE
No supported EME version

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#78]
When running the Android PWA on Chrome 112.0.5615.138 (Official Build) (64-bit) for Windows, the following error is logged in the console
````
bug.js:169 [22][Protection] No supported version of EME detected on this user agent! - Attempts to play encrypted content will fail! 
S
````

Should it be possible to play DRM protected content on a Windows 10 PC?

**Comment by juhajoki** [comment]
Error message comes from dash.js. In our experience, widevine L3 and clearkey should work in a PC environment. Playready might be a struggle. 

More information to be added...

**Comment by sofia-tsa** [comment]
Playready should be available when using MS Edge browser

**Comment by paulhiggs** [comment]
This message no longer shows up with the new location - https://dvb-i-reference.dvb.org/client/frontend/android/player.html
