### ISSUE TITLE
most of the services in service list in github are not available any more

### ISSUE THREAD

**Issue by jpiesing** [DVBProject/DVB-I-Reference-Client#79]
It has been suggested that most or all of the services in the default service list in github are not available any more.

Of course this doesn't matter to people who live and breathe DVB-I who will have their own setup but there are other people as well - both 1) people who only occasionally would want to demonstrate DVB and 2) people new to DVB who discover the reference app or are referred to the reference app. Having the latter get a black screen is really, really bad.

There should be a clear default service list that is more proactively curated - where services are removed when they are no longer available.

**Comment by paulhiggs** [comment]
I will remove disfunctional services from service lists.
