### ISSUE TITLE
Service logo does not resize

### ISSUE THREAD

**Issue by crittlc** [DVBproject/DVB-I-Reference-Client#8]
When a service is selected, its logo corerctly appears at the bottom-left corner of the screen.
But if the original image is too big, it does not properly resize to the menuitem_chicon portion.

(Tested on the Android version)

**Comment by juhajoki** [comment]
we will fix this in a future release that the logo is automatically resized. 
For now, please use 98x55px size logo.

**Comment by paulhiggs** [comment]
Please take a look at section 5.2.8.2.2 for how server side image processing to obtain the appropriate resolution can be obtained
