### ISSUE TITLE
links in README.md point to stage.sofiadigital.fi

### ISSUE THREAD

**Issue by jpiesing** [DVBProject/DVB-I-Reference-Client#81]
The links in README.md point to stage.sofiadigital.fi.
We should consider if they should point to a dvb.org web site of some descritption.
Ideally the files concerned would be hosted on a dvb.org web site.
If that's too much work to justify this far into the project then we should at least consider a redirect so that the URLs in the page are dvb.org.

**Comment by paulhiggs** [comment]
If we can get a web server with PHP support setup in the dvb.org domain, then we can certainly use it rather than the Sofia Digital staging  server

**Comment by juhajoki** [comment]
I think simplest one regarding initial effort and maintenance is for us to create a new virtual server for the backend and client and point that to something.dvb.org. 

also note that only the backend uses php anymore.

**Comment by paulhiggs** [comment]
Lets check with Eoghan on what hosts we can add into the `dvb.org` domain. Probably aim for `dvbi-reference.dvb.org`

**Comment by eoghan-dvb** [comment]
We can add whatever subdomains we want to dvb.org. The domain is with Network Services but the DNS is managed by the EBU, so I would need to make the request there. 

@juhajoki - are you proposing that Sofia Digital would create a new virtual server?
@paulhiggs - we could explore whether something could be hosted on the server used for either the public DVB website or for Causeway. This would probably require additional once-off and/or ongoing payment to VTM Group.

**Comment by juhajoki** [comment]
@eoghan-dvb yes - this can be done under our maintenance agreement, and will be simplest approach from our pov. Access to this server box can be granted to all necessary parties and it can be registered under the dvb domain. 

Under the agreement we'd maintain the live server (security patches) and app and content updates would be provided by Sofia and virtually anyone (after reviews) through the github instance.

**Comment by eoghan-dvb** [comment]
If everyone is in agreement with this approach, I would just need to know what entries are required in the DNS for dvb.org and when they should be activated. Paul suggested above that we use dvbi-reference.dvb.org. We could also consider dvb-i-reference.dvb.org perhaps?

**Comment by jpiesing** [comment]
> If everyone is in agreement with this approach, I would just need to know what entries are required in the DNS for dvb.org and when they should be activated. Paul suggested above that we use dvbi-reference.dvb.org. We could also consider dvb-i-reference.dvb.org perhaps?

I have no opinion on the name. It can be activated in DNS as soon as reasonably practical. The real activation will be a pull request to README.md which changes the links over and we don't have to do that until everything is ready.

**Comment by paulhiggs** [comment]
Consensus on `dvb-i-reference.dvb.org`

@eoghan-dvb I presume we need the virtual host information from Sofia Digital before creating this entry in the DVB DNS records.

**Comment by paulhiggs** [comment]
@sofia-tsa Please deploy the commit for this issue on the new server [https://dvb-i-reference.dvb.org/client/]

**Comment by paulhiggs** [comment]
Links in readme now refer to https://dvb-i-reference.dvb.org/
