### ISSUE TITLE
poor 'out of the box' experience for someone new to DVB-I

### ISSUE THREAD

**Issue by jpiesing** [DVBProject/DVB-I-Reference-Client#82]
The out of the box experience with the reference app isn't great for someone new to DVB-I.

If you follow the link, you get taken to a page offering service list selection. People new to DVB-I may not fully understand this and certainly won't have the context to choose a particular service list. IMHO a default service list should be selected and perhaps some kind of banner page shown as an overlay. The banner could then indicate that other service lists are available, where to find the menu to choose them and perhaps some context as to why they may want to choose one of them. The banner could also contain other information someone new to this might find helpful.

As well as a default service list  being selected, a default service should be selected so that following the link from README.md results in someone seeing video and audio.

**Comment by sofia-tsa** [comment]
I'll implement the default service list selection and an information banner when starting the app for the first time

**Comment by sofia-tsa** [comment]
Default service selection with the mobile version ( https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/frontend/android/player.html ) will not work due to the autoplay behaviour: https://developer.chrome.com/blog/autoplay/
It should work if the user installs the reference application as a PWA but default service selection will not work without user interaction when opening the app directly from the link

**Comment by paulhiggs** [comment]
I would suggest that we add a parameter to the URL, i.e. `?mode=demo` that can select one of the service lists.
The DVB-I spec does not have a 'default service list' notion

**Comment by sofia-tsa** [comment]
or could we just provide the service list URI as a parameter? for example:
`?servicelist=https%3A%2F%2Fstage.sofiadigital.fi%2Fdvb%2Fdvb-i-reference- application%2Fbackend%2Fservicelist.php%3Flist%3Dexample.xml`

**Comment by sofia-tsa** [comment]
> > Default service selection with the mobile version ( https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/frontend/android/player.html ) will not work due to the autoplay behaviour: https://developer.chrome.com/blog/autoplay/ It should work if the user installs the reference application as a PWA but default service selection will not work without user interaction when opening the app directly from the link
> 
> Could this be mentioned in the banner so people know they have to interact on a mobile?

We could make the banner modal, so the user needs to click OK button to close it. Then we can do a service selection as the user has interacted with the application. Maybe show the modal only when the users starts the application for the first time, it might be annoying to click OK every time.

**Comment by sofia-tsa** [comment]
![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/12542453/fc4abb79-147d-40f4-a307-772fd1dd208c)

Mayber something like this. The text is just something quick I came up with, that can be changed. But the video starts playing after clicking the Ok button.

**Comment by jpiesing** [comment]
> ![image](https://user-images.githubusercontent.com/12542453/249113952-fc4abb79-147d-40f4-a307-772fd1dd208c.png)
> 
> Mayber something like this. The text is just something quick I came up with, that can be changed. But the video starts playing after clicking the Ok button.

Not bad. It might be better to re-phrase the top line like this & add a small DVB logo.

> Welcome to the DVB Project's DVB-I reference application.

**Comment by paulhiggs** [comment]
First time use screen now looks like this....
 
![image](https://github.com/DVBProject/DVB-I-Reference-Client/assets/3158807/ebff51a6-a073-4467-918f-4819b525cb73)

**Comment by paulhiggs** [comment]
Previous addition of banner page, and PR #103 cover all raised items.

**Comment by paulhiggs** [comment]
Resolved with PR #103
