### ISSUE TITLE
HTTP 301 response code is not followed

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#84]
Many service list providers use HTTP 301 to redirect from a permanent alias URL to an operational URL. 
The Reference Client should follow the redirection offered by HTTP 301 "Moved Permanently".

**Comment by sofia-tsa** [comment]
If the reference app is used over https:// then any service list requests using http:// will not work, even if it is just a redirect to https://

**Comment by paulhiggs** [comment]
> 

Agreed, but 301 can also be used for http->http or https->https aliasing

**Comment by paulhiggs** [comment]
Some [atricles](https://stackoverflow.com/questions/282429/returning-redirect-as-response-to-ajax-fetch-xhr-etc-request/2573589#2573589) suggest that the Query $.get() api should follow redirects, but perhaps only 302, 303, 307, 308

**Comment by sofia-tsa** [comment]
I did a quick test, seems like 301 redirect works but the 301 response needs to have the Access-Control-Allow-* headers set correctly. Also,if the redirect is to a different domain/protocol, then the service list URL needs to handle the preflight OPTIONS-request.

**Comment by paulhiggs** [comment]
Lets close this - it seems to be related more to webserver configuration of CORS than the DVB-I Reference Client.
