### ISSUE TITLE
support &delivery= query parameter

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#86]
Allow the DVB-I client to include the &delivery= query parameter in the service list registry request.

Should include the value choice for this in the local settings and then use it in subsequent SLR requests.
Mini SLR provided in `backend/servicelist_registry.php` to be supported. Equivelant update in the [DVB-I Reference CSR](https://github.com/DVBProject/DVB-I-Reference-CSR) is optional.

**Comment by sofia-tsa** [comment]
CSR should already support the Delivery-parameter, for example: https://csr.dtv.fi/api/query?Delivery=dvb-t

**Comment by paulhiggs** [comment]
It needs to be supported in the [DVB-I Reference Client CSR](https://github.com/DVBProject/DVB-I-Reference-Client/blob/master/backend/servicelist_registry.php) not the DVB-I Reference CSR.

**Comment by sofia-tsa** [comment]
Yes, I will start implementing the Delivery-parameter now to the Reference Client. Just added the note because I remembered implementing the parameter already in the CSR side.

**Comment by sofia-tsa** [comment]
There are no Delivery elements in the [CSR List](https://github.com/DVBProject/DVB-I-Reference-Client/blob/master/backend/slepr-master.xml), should we add those? Also the CSR List is using the original A177r0 schema, should we update it to A177r5?

**Comment by sofia-tsa** [comment]
Implemented in 2f5122072ac02e7a4ce97df2ed2b7e0da8bf751c

**Comment by sofia-tsa** [comment]
Implemented in https://github.com/DVBProject/DVB-I-Reference-Client/releases/tag/2.28
