### ISSUE TITLE
support 'published' schemas

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#88]
A177r6 has updates to own schemas (service list discovery and service list), the content guide metadata (through TV-Anytime updates) and in its own data-types schema - all of which have versioning updates in their `targetNamespace`

New target namespace should be used - there is no requirement to retain support for previous versions (covered by a 'final A177r4' release tag)

**Comment by paulhiggs** [comment]
As we have just approved the A177r6 bluebook publication, we should move to that schema and remove support for old versions

**Comment by jpiesing** [comment]
> As we have just approved the A177r6 bluebook publication, we should move to that schema and remove support for old versions

Do we want to be quite so quick in removing support for old versions. What versions are used by the service lists we normally use for demos etc?

**Comment by juhajoki** [comment]
Old versions should remain available by referencing to the appropriate tag in the repository.

**Comment by paulhiggs** [comment]
Yes, the intent of this  was to avoid the reference client containing code such as 
````
if version=="r1" {} else if version=="r4" {} else if version=="r6" {}
````

We already had some support for r1/r4 in the reference client, but carrying that forward to r6 is complicated by the many schema updates between these revisions.

**Comment by paulhiggs** [comment]
No more schema updates are made, so the branch `a177r6_schema` can now be merged with `master`

**Comment by paulhiggs** [comment]
[Codebase](https://github.com/DVBProject/DVB-I-Reference-Client) and [reference implementation](https://dvb-i-reference.dvb.org/client/) are now updated with r6 schemas
