### ISSUE TITLE
Server side service list construction

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#89]
Allow the DVB-I client to enter a postcode of some DVB-T multiplex information and receive a service list suitably tailored.
For reference client purposes, this could be from a sonatrained set of configurable values.

See A177r6 clause 5.6.4.2 for Server-side Region Selection using postcode information and clause 5.6.4.3 for Server-side Region Selection using reception information

**Comment by sofia-tsa** [comment]
How is the postcode validation meant to work? Drop all the regions that don't match the postcode? But if the matching region is a tertiary sub region, we need to include the parent regions? Should the parent regions be marked with selectable=false if the parent regions do not match the postcode?

**Comment by paulhiggs** [comment]
A177 clause 5.6.3.3 says

> A DVB-I client may ask the user to enter their postcode. A DVB-I client can check for matches between the user entered postcode and the postcodes associated with regions in the region list. The region that matches with the user's postcode should automatically be selected by the DVB-I client. When there is more than one region matching the user's postcode, the DVB-I client should offer manual selection between those regions.

So, only display regions that match the specified postcode!

**Comment by sofia-tsa** [comment]
Example servicelist with regions, android and hbbtv-client implementation added
