### ISSUE TITLE
Text drawn in wrong place on Android

### ISSUE THREAD

**Issue by jpiesing** [DVBproject/DVB-I-Reference-Client#9]
See attached screen dump from my android phone . The channel name has been written one row below where it should have been.

![Screenshot_20200224-131648](https://user-images.githubusercontent.com/8490792/75151915-1a405500-5708-11ea-986c-47e792e0f7a1.png)

**Comment by juhajoki** [comment]
which phone is it? 
We could shorten the name a bit as a workaround.

**Comment by jpiesing** [comment]
![Screenshot_20200224-133721](https://user-images.githubusercontent.com/8490792/75153111-d569ed80-570a-11ea-9c3c-fc69915205be.png)

**Comment by jpiesing** [comment]
> We could shorten the name a bit as a workaround.

If that would avoid it happening on all phones then fine. If that fix would be specific to phones of a certain screen size & it might still happen on other screen sizes then perhaps not.

**Comment by juhajoki** [comment]
Looks like the displaysize setting "larger or largest" breaks the layout. We will change it so that the service name is cut to avoid it being drawn incorrectly. (or otherwise adjusted, I'll let the layout master decide the best solution)

**Comment by paulhiggs** [comment]
![2020-02-24 15 27 03](https://user-images.githubusercontent.com/3158807/75188518-29dd8f00-5744-11ea-90c2-ebd983f6e6bf.jpg)
Looks OK on my Huawei Mate 10 Pro phone - screen resolution is 1080x2160 pixels at 480dpi

**Comment by paulhiggs** [comment]
@jpiesing - please comment on whether this has been resolved, i presume that this is HTML 'flow' related

**Comment by jpiesing** [comment]
Fixed
