### ISSUE TITLE
Parental rating restrictions on playout

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#90]
DVB-I client is configured with a maximum unrated age value (maxUnratedAge). If program rating (programAge) exceeds maxUnratedAge then unlock PIN is requested. On program boundary, if programAge is greater than maxUnratedAge and current (new) program genre is different from previous program genre then unlock PIN is requested.

_Test assets_

* Test stream with alternating rated and non-rated content (1 minute each) and applicable EPG metadata. Each time the rated content arrives, an unlocking PIN is requested. If not provided the playout is blocked.

  * Rated programs specified with &lt;ProgramInformation&gt;&lt;BasicDescription&gt;&lt;ParentalGuidance&gt;&lt;mpeg7:MinimumAge&gt;18

  * Non rated programs specified with either

    - no &lt;ParentalGuidance&gt; or

    -  &lt;ProgramInformation&gt;&lt;BasicDescription&gt;&lt;ParentalGuidance&gt;&lt;mpeg7:MinimumAge&gt;4

* Test stream with rated programs denoted with &lt;ProgramInformation&gt;&lt;BasicDescription&gt;&lt;ParentalGuidance&gt;&lt;mpeg7:MinimumAge>18 (alternating every 1 minute). DVB-I client should seek PIN code when program changes with same or higher rating.

**Comment by sofia-tsa** [comment]
Implemented in  https://github.com/DVBProject/DVB-I-Reference-Client/releases/tag/2.28
