### ISSUE TITLE
Host reference client on DVB branded servers

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#91]
Ensure that the DVB-I operational component is available at a DVB URL, i.e. `dvbi-rc.dvb.org`

**Comment by juhajoki** [comment]
@paulhiggs who decides the final URL? We can finalize this quickly as soon as we settle on the URL.

**Comment by jpiesing** [comment]
I would be happy for @paulhiggs to decide the final URL.

**Comment by paulhiggs** [comment]
See also #81 
I thinl `dvb-i-reference.dvb.org` is the best option.

**Comment by eoghan-dvb** [comment]
I can have the DNS (which is managed by the EBU for dvb.org) updated with a new A record pointing to 167.235.218.6

Should this be: 
dvb-i-reference.dvb.org (which was the last suggestion from Paul above)
or 
dvb-i-reference-client.dvb.org (suggested by Juha in his email)?

You also need to tell me what certificate is needed.

**Comment by eoghan-dvb** [comment]
@juhajoki @paulhiggs - Not sure if I should have mentioned you above so that you'd see this.

**Comment by juhajoki** [comment]
I'd go with Paul's suggestion. My suggestion was a mistake and is not suitable for the hosting since it is more than just the client.

**Comment by eoghan-dvb** [comment]
The A record has been added for dvb-i-reference.dvb.org

**Comment by paulhiggs** [comment]
See also #81

**Comment by paulhiggs** [comment]
Let's put the reference client code in the /client/ directory, so it's /client/frontend and /client/backend

**Comment by paulhiggs** [comment]
Reference client front end application is now moved

- Android app - https://dvb-i-reference.dvb.org/client/frontend/android/
- Browser - https://dvb-i-reference.dvb.org/client/frontend/android/player.html
- Service List editor - https://dvb-i-reference.dvb.org/client/backend
