### ISSUE TITLE
URI Linkage Descriptor in NIT

### ISSUE THREAD

**Issue by paulhiggs** [DVBProject/DVB-I-Reference-Client#92]
New transport stream as part of the DVB-I reference client project.

TS with a URI linkage descriptor in the 1st loop of NIT where `uri_linkage_type = 0x03`
<html>
DVB-I_info() contains:<br/>
<ul>
       <li>end_point_type=0x03
       <li>valid (>0 chars) service_name
       <li>valid (>0 chars) service_provider_name
</ul></html>

**Comment by sofia-tsa** [comment]
What service and provider name should we use?  I assume the idea is that the client searches the CSR for the service list based on the service and providers names in the descriptor.

**Comment by paulhiggs** [comment]
In this case, the service list name and service list provider name are provided in the NIT/BAT along with the service list URR - no CSR necessary. This item should have 2-3 entried woth dfferent name/provider/url value that would be presented to the user to 'select' - at which time the url would be loaded!

**Comment by sofia-tsa** [comment]
Oh, now I see. It's the URI linkage descriptor (extension descriptor, tag 0x7F, extension tag 0x13) that contains the service list URI and the name  and provider are in the private data DVB-I_info()-element.

**Comment by sofia-tsa** [comment]
I have created a new TS with the URI linkage descriptor. The URI is "https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/servicelist.php?list=example.xml", name is "DVB-I Reference application example list" and the provider is "DVB". Once the dvb-i-reference.dvb.org site is up and running we will update all the TS files to point to the new site.

**Comment by juhajoki** [comment]
Stream is available here: https://cloud.sofiadigital.fi/index.php/s/dvbi-2023
password is: dvb-i-2023

**Comment by paulhiggs** [comment]
Looks good to me.
Shows in [tstables](https://tsduck.io/commands/) as
````
* NIT Actual, TID 64 (0x40), PID 16 (0x0010)
  Version: 1, sections: 1, total size: 220 bytes
  - Section 0:
    Network Id: 1 (0x0001)
    Network information:
    - Descriptor 0: Network Name (0x40, 64), 19 bytes
      Name: "DVB-I Demonstrator"
    - Descriptor 1: Extension Descriptor (0x7F, 127), 151 bytes
      Extended descriptor: URI Linkage (0x13, 19)
      URI linkage type: 0x03 (DVB-I)
      URI: https://stage.sofiadigital.fi/dvb/dvb-i-reference-application/backend/servicelist.php?list=example.xml
      End point type: 0x03 (DVB-I Service List with list name and provider name)
      Service list name: DVB-I Reference application example list
      Service list provider name: DVB
    Transport Stream Id: 4097 (0x1001), Original Network Id: 8916 (0x22D4)
    - Descriptor 0: Service List (0x41, 65), 6 bytes
      Service id: 62 (0x003E), Type: 0x19 (Advanced codec HD digital television service)
      Service id: 74 (0x004A), Type: 0x19 (Advanced codec HD digital television service)
    - Descriptor 1: Private Data Specifier (0x5F, 95), 4 bytes
      Specifier: 0x00000029 (NorDig)
    - Descriptor 2: NorDig Logical Channel (V1) (0x83, 131), 8 bytes
      Service Id:    62 (0x003E), Visible: 1, Channel number:   1
      Service Id:    74 (0x004A), Visible: 1, Channel number:   2
````
